version: '3.9'

volumes:
  certbotdata:
  gtfsapidb-live:
  gtfsapidb-next:

networks:
  backend-network:
    driver: bridge

services:
  #
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE

  nginx:
    image: ghcr.io/carrismetropolitana/schedules-api-nginx:latest
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    networks:
      - backend-network
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api-live:
    image: ghcr.io/carrismetropolitana/schedules-api-api:latest
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    networks:
      - backend-network
    environment:
      - GTFSAPIDB_HOST=gtfsapidb-live
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidbname

  api-next:
    image: ghcr.io/carrismetropolitana/schedules-api-api:latest
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    networks:
      - backend-network
    environment:
      - GTFSAPIDB_HOST=gtfsapidb-next
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidbname

  daemon-live:
    image: ghcr.io/carrismetropolitana/schedules-api-daemon:latest
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./data-temp/:/data-temp
    environment:
      - GTFSAPIDB_HOST=gtfsapidb-live
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidbname
      - GTFSPARSEDB_HOST=gtfsparsedb-live
      - GTFSPARSEDB_USER=gtfsparsedbuser
    networks:
      - backend-network

  daemon-next:
    image: ghcr.io/carrismetropolitana/schedules-api-daemon:latest
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./data-temp-next/:/data-temp
    environment:
      - GTFSAPIDB_HOST=gtfsapidb-next
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidbname
      - GTFSPARSEDB_HOST=gtfsparsedb-next
      - GTFSPARSEDB_USER=gtfsparsedbuser
    networks:
      - backend-network

  gtfsapidb-live:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - gtfsapidb-live:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gtfsapidbuser
      - MONGO_INITDB_ROOT_PASSWORD=gtfsapidbpassword
    networks:
      - backend-network

  gtfsapidb-next:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - gtfsapidb-next:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gtfsapidbuser
      - MONGO_INITDB_ROOT_PASSWORD=gtfsapidbpassword
    networks:
      - backend-network

  gtfsparsedb-live:
    image: mysql
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/gtfsparsedb/:/etc/mysql/conf.d/
      - ./data-temp/:/data-temp
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gtfsparsedbname
    networks:
      - backend-network

  gtfsparsedb-next:
    image: mysql
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/gtfsparsedb/:/etc/mysql/conf.d/
      - ./data-temp/:/data-temp
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gtfsparsedbname
    networks:
      - backend-network
