version: '3.9'

volumes:
  certbotdata:
  gtfsapidb:

networks:
  backend-network:
    driver: bridge

services:
  #
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  nginx:
    image: nginx:stable
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    env_file:
      - ./.env
    networks:
      - backend-network
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''sed -i "s/UPTIME_MONITOR_HEADER/${UPTIME_MONITOR_HEADER}/g" "/etc/nginx/conf.d/nginx.conf" && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api:
    image: ghcr.io/carrismetropolitana/schedules-api:v2
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    networks:
      - backend-network
    environment:
      - GTFSAPIDB_HOST=gtfsapidb
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidb
    env_file:
      - ./.env

  daemon:
    image: ghcr.io/carrismetropolitana/schedules-daemon:v2
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./data-temp/:/data-temp
    environment:
      - GTFS_URL=https://github.com/carrismetropolitana/gtfs/raw/live/CarrisMetropolitana.zip
      - GTFSAPIDB_HOST=gtfsapidb
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidb
      - GTFSPARSEDB_HOST=gtfsparsedb
      - GTFSPARSEDB_USER=gtfsparsedbuser
      - GTFSPARSEDB_PASSWORD=gtfsparsedbpassword
    networks:
      - backend-network

  gtfsapidb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - gtfsapidb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gtfsapidbuser
      - MONGO_INITDB_ROOT_PASSWORD=gtfsapidbpassword
    networks:
      - backend-network

  gtfsparsedb:
    image: postgres
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./gtfsparsedb/:/etc/postgresql/
      - ./data-temp/:/data-temp
    environment:
      - POSTGRES_USER=gtfsparsedbuser
      - POSTGRES_PASSWORD=gtfsparsedbpassword
    networks:
      - backend-network
