version: '3.8'

volumes:
  certbotdata:
  gtfsapidb:
  settingsdb:

networks:
  backend-network:
    driver: bridge

services:
  #
  nginx:
    image: nginx:stable
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/nginx:/etc/nginx/conf.d
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    networks:
      - backend-network
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api:
    build: ./api/
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    depends_on:
      - nginx
    networks:
      - backend-network
    ports:
      - $API_PORT
    env_file: ./.env
    environment:
      - SETTINGSDB_HOST=$SETTINGSDB_HOST
      - SETTINGSDB_USER=$SETTINGSDB_USER
      - SETTINGSDB_PASSWORD=$SETTINGSDB_PASSWORD
      - SETTINGSDB_NAME=$SETTINGSDB_NAME
      - GTFSAPIDB_HOST=GTFSAPIdb
      - GTFSAPIDB_USER=$GTFSAPIDB_USER
      - GTFSAPIDB_PASSWORD=$GTFSAPIDB_PASSWORD
      - GTFSAPIDB_NAME=$GTFSAPIDB_NAME

  daemon:
    build: ./daemon/
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./data-temp/:/data-temp
    env_file: ./.env
    environment:
      - SETTINGSDB_HOST=$SETTINGSDB_HOST
      - SETTINGSDB_USER=$SETTINGSDB_USER
      - SETTINGSDB_PASSWORD=$SETTINGSDB_PASSWORD
      - SETTINGSDB_NAME=$SETTINGSDB_NAME
      - GTFSAPIDB_HOST=$GTFSAPIDB_HOST
      - GTFSAPIDB_USER=$GTFSAPIDB_USER
      - GTFSAPIDB_PASSWORD=$GTFSAPIDB_PASSWORD
      - GTFSAPIDB_NAME=$GTFSAPIDB_NAME
      - GTFSPARSEDB_HOST=$GTFSPARSEDB_HOST
      - GTFSPARSEDB_USER=root
    networks:
      - backend-network

  # dashboard:
  #   build: ./config/
  #   restart: unless-stopped
  #   logging:
  #     options:
  #       max-size: '1m'
  #       max-file: '1'
  #   depends_on:
  #     - nginx
  #   networks:
  #     - backend-network
  #   ports:
  #     - $CONFIG_PORT
  #   env_file: ./.env
  #   environment:
  #     - SETTINGSDB_HOST=$SETTINGSDB_HOST
  #     - SETTINGSDB_USER=$SETTINGSDB_USER
  #     - SETTINGSDB_PASSWORD=$SETTINGSDB_PASSWORD
  #     - SETTINGSDB_NAME=$SETTINGSDB_NAME

  settingsdb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - settingsdb:/data/db
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$SETTINGSDB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$SETTINGSDB_PASSWORD
    networks:
      - backend-network

  gtfsapidb:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - gtfsapidb:/data/db
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$GTFSAPIDB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$GTFSAPIDB_PASSWORD
    networks:
      - backend-network

  gtfsparsedb:
    image: mysql
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/gtfsparsedb/:/etc/mysql/conf.d/
      - ./data-temp/:/data-temp
    env_file: ./.env
    environment:
      # - MYSQL_HOST=$GTFSAPIDB_USER
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=$GTFSPARSEDB_NAME
    networks:
      - backend-network
    ports:
      - 3306

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: unless-stopped
  #   logging:
  #     options:
  #       max-size: '1m'
  #       max-file: '1'
  #   depends_on:
  #     - settingsdb
  #     - gtfsapidb
  #     - gtfsparsedb
  #   networks:
  #     - backend-network
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1
