version: '3.9'

volumes:
  certbotdata:
  gtfsapidb-production:
  gtfsapidb-staging:

networks:
  backend-network:
    driver: bridge

services:
  #
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_CLEANUP=TRUE
      - WATCHTOWER_INCLUDE_STOPPED=TRUE
      - WATCHTOWER_REVIVE_STOPPED=TRUE
      - WATCHTOWER_ROLLING_RESTART=TRUE

  nginx:
    image: nginx:stable
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/nginx:/etc/nginx/conf.d
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    networks:
      - backend-network
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./options/letsencrypt:/etc/letsencrypt
      - certbotdata:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  api-production:
    image: ghcr.io/carrismetropolitana/schedules-api-api:production
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    networks:
      - backend-network
    environment:
      - GTFSAPIDB_HOST=gtfsapidb-production
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidb

  api-staging:
    image: ghcr.io/carrismetropolitana/schedules-api-api:staging
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    networks:
      - backend-network
    environment:
      - GTFSAPIDB_HOST=gtfsapidb-staging
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidb

  daemon-production:
    image: ghcr.io/carrismetropolitana/schedules-api-daemon:production
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./data-temp/production/:/data-temp
    environment:
      - GTFS_URL=https://github.com/carrismetropolitana/gtfs/raw/live/CarrisMetropolitana.zip
      - GTFSAPIDB_HOST=gtfsapidb-production
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidb
      - GTFSPARSEDB_HOST=gtfsparsedb-production
      - GTFSPARSEDB_NAME=gtfsparsedb
      - GTFSPARSEDB_USER=root
    networks:
      - backend-network

  daemon-staging:
    image: ghcr.io/carrismetropolitana/schedules-api-daemon:staging
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./data-temp/staging/:/data-temp
    environment:
      - GTFS_URL=https://github.com/carrismetropolitana/gtfs/raw/next/CarrisMetropolitana.zip
      - GTFSAPIDB_HOST=gtfsapidb-staging
      - GTFSAPIDB_USER=gtfsapidbuser
      - GTFSAPIDB_PASSWORD=gtfsapidbpassword
      - GTFSAPIDB_NAME=gtfsapidb
      - GTFSPARSEDB_HOST=gtfsparsedb-staging
      - GTFSPARSEDB_NAME=gtfsparsedb
      - GTFSPARSEDB_USER=root
    networks:
      - backend-network

  gtfsapidb-production:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - gtfsapidb-production:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gtfsapidbuser
      - MONGO_INITDB_ROOT_PASSWORD=gtfsapidbpassword
    networks:
      - backend-network

  gtfsapidb-staging:
    image: mongo
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - gtfsapidb-staging:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=gtfsapidbuser
      - MONGO_INITDB_ROOT_PASSWORD=gtfsapidbpassword
    networks:
      - backend-network

  gtfsparsedb-production:
    image: mysql
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/gtfsparsedb/:/etc/mysql/conf.d/
      - ./data-temp/production/:/data-temp
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gtfsparsedb
    networks:
      - backend-network

  gtfsparsedb-staging:
    image: mysql
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - ./options/gtfsparsedb/:/etc/mysql/conf.d/
      - ./data-temp/staging/:/data-temp
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gtfsparsedb
    networks:
      - backend-network
