version: '3.9'

volumes:
  serverdb:

secrets:
  realtimedbkey:
    file: REALTIMEDB.key

services:
  #

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  serverdb:
    image: redis:alpine
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - serverdb:/data
    environment:
      - REDIS_ARGS=--save 5 1
    ports:
      - "6379:6379"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  networkdb:
    image: postgres:alpine
    restart: unless-stopped
    logging:
      options:
        max-size: '1m'
        max-file: '1'
    environment:
      - POSTGRES_USER=networkdbuser
      - POSTGRES_PASSWORD=networkdbpassword
    ports:
      - "5432:5432"

  # # # # # # # # # # # # # # # # # # # # #
  # # # # # # # # # # # # # # # # # # # # #

  # parse-network:
  #   image: ghcr.io/carrismetropolitana/api-parse-network:beta
  #   restart: unless-stopped
  #   logging:
  #     options:
  #       max-size: '1m'
  #       max-file: '1'
  #   env_file:
  #     - ./.env
  #   environment:
  #     - SERVERDB_HOST=serverdb
  #     - NETWORKDB_HOST=networkdb
  #     - NETWORKDB_USER=networkdbuser
  #     - NETWORKDB_PASSWORD=networkdbpassword
